TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/riquipa/development/projects/webcomponent-vl-ui-tooltip/node_modules/minify/lib/minify.js:5:33)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at uglifyFiles (/Users/riquipa/development/projects/webcomponent-vl-ui-tooltip/node_modules/minify/bin/minify.js:77:20)
    at minify (/Users/riquipa/development/projects/webcomponent-vl-ui-tooltip/node_modules/minify/bin/minify.js:56:5)
