import{VlRegisterElement,VlElement}from"/node_modules/vl-ui-core/vl-core.js";(()=>{function t(t,i){if(!document.head.querySelector("#"+t)){const o=e(t,i);document.head.appendChild(o)}}function e(t,e){const i=document.createElement("script");return i.setAttribute("src",e),i}t("vl-util.js","/node_modules/@govflanders/vl-ui-util/dist/js/util.js"),t("tooltip.js","/node_modules/tooltip.js/dist/umd/tooltip.js"),t("popper.js","/node_modules/popper.js/dist/umd/popper.js"),t("vl-tooltip.js","/node_modules/@govflanders/vl-ui-tooltip/dist/js/tooltip.js")})();export class VlTooltip extends VlElement(HTMLElement){constructor(){super(`
      <style>
          @import "/node_modules/vl-ui-tooltip/style.css";
      </style>
    `);this._addStyleLink()}connectedCallback(){if(!this._isStatic){this._applyDataTooltipAttributes()}}static get _observedAttributes(){return["static","placement"]}get _isStatic(){return this.hasAttribute("static")}get _placement(){return this.getAttribute("placement")}get _staticTooltipElement(){return this._shadow.querySelector(".vl-tooltip")}_applyDataTooltipAttributes(){this.parentNode.setAttribute("data-vl-tooltip","");this.parentNode.setAttribute("data-vl-tooltip-placement",this._placement);this.parentNode.setAttribute("data-vl-tooltip-content",this.textContent)}_removeDataTooltipAttributes(){this.parentNode.removeAttribute("data-vl-tooltip");this.parentNode.removeAttribute("data-vl-tooltip-placement");this.parentNode.removeAttribute("data-vl-tooltip-content")}_getStaticTooltipTemplate(){return this._template(`
        <div class="vl-tooltip vl-tooltip--static">
          <div class="vl-tooltip__inner">
            <slot></slot>
          </div>
          <div class="vl-tooltip__arrow"></div>
        </div>
     `)}_placementChangedCallback(oldValue,newValue){if(this._isStatic){this._staticTooltipElement.setAttribute("x-placement",newValue)}else{this.parentNode.setAttribute("data-vl-tooltip-placement",newValue)}}_staticChangedCallback(oldValue,newValue){if(this._staticTooltipElement){this._staticTooltipElement.remove()}if(newValue!=undefined){this._removeDataTooltipAttributes();const tooltipTemplate=this._getStaticTooltipTemplate();this._shadow.appendChild(tooltipTemplate);this._staticTooltipElement.setAttribute("x-placement",this._placement)}else{this._applyDataTooltipAttributes()}}get _stylePath(){return"/node_modules/vl-ui-tooltip/style.css"}};VlRegisterElement(()=>{customElements.define("vl-tooltip",VlTooltip)});